# Use Node.js as the base image
FROM node:20-alpine as development

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your application
COPY . .

# Expose port for Vite (default: 5173)
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
